project_id = "erqvlccnuqjyszayxfuc"

[functions.geo-ip]
verify_jwt = false

[functions.save-postcode]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.paynl-webhook]
verify_jwt = false

[functions.get-print-queue]
verify_jwt = false

[functions.mark-printed]
verify_jwt = false

[functions.generate-print-html]
verify_jwt = false

[functions.print-client-settings]
verify_jwt = false

[functions.print-client-update]
verify_jwt = false

[functions.request-test-print]
verify_jwt = false
